version: '3'
services:
    postgres:
        image: postgres
        container_name: airflow_db
        restart: always
        shm_size: 128mb
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow_db
        volumes:
            - ./init_postgreSQL_airflow.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 5432:5432